on:  # Add this key to specify workflow triggers
  push:  # Example trigger: run the workflow on push events
    branches: [main]  # Specify the branches to trigger on
env:
  DBX_ACCESS_TOKEN: ${{ secrets.DBXACCESSTOKEN }}
