on:  # Define the events that trigger the workflow
  push:  # Example: Trigger on every push to the repository
    branches: [main]  # Specify the branches to watch (optional)
  # You can add other events as needed (e.g., pull_request, schedule)

jobs:
  build:  # Or any other relevant job name
    runs-on: ubuntu-latest  # Or your preferred runner
    steps:
      - uses: actions/checkout@v3
        env:
          DBX_ACCESS_TOKEN: ${{ secrets.DBX_ACCESS_TOKEN }}  # Set the secret as an environment variable
